### ISSUE TITLE
401

### ISSUE THREAD

**Issue by GutsyHeart** [hagaygo/tvheadendm3usync#4]
```
dotnet TVHeadEndM3USync.dll http://tv.local Playlist-03.m3u 24h admin 1234
Unhandled exception. System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at TVHeadEndM3USync.TVHeadEnd.TVHClient.GetJSON(HttpWebRequest wr) in C:\Users\hagay\Source\Repos\TVHeadEndM3USync\TVHeadEnd\TVHClient.cs:line 147
   at TVHeadEndM3USync.TVHeadEnd.TVHClient.GetNetworks() in C:\Users\hagay\Source\Repos\TVHeadEndM3USync\TVHeadEnd\TVHClient.cs:line 158
   at TVHeadEndM3USync.Program.GetNetwork(String networkNameToSync, TVHClient cli) in C:\Users\hagay\Source\Repos\TVHeadEndM3USync\Program.cs:line 140
   at TVHeadEndM3USync.Program.Main(String[] args) in C:\Users\hagay\Source\Repos\TVHeadEndM3USync\Program.cs:line 45
[1]    7207 IOT instruction  dotnet TVHeadEndM3USync.dll http://tv.local Playlist-03.m3u 24h admin 1234
```

**Comment by hagaygo** [comment]
Hi

Your error indicates a 401 response which mean the http call was Unauthorized.

If you are sure your username and password are correct, you should try change tvheadend's authenication to "both plain and digest" as stated on the readme of this app.
